### ISSUE TITLE
Add: create stopwatch

### ISSUE THREAD

**Issue by mogiiee** [IEEE-VIT/concy-bot#1]
Create a function of a stopwatch which when called on discord will start a timer (in minutes), and will stop when the user gives the stop command.

**Comment by sanz17** [comment]
i want to solve this issue

**Comment by Bhargav-bit800** [comment]
@mogiiee can i take up this issue?

**Comment by hg242322** [comment]
I am assigning this issue to you. All the Best !!

**Comment by mogiiee** [comment]
i am assigning you both the project.
