### ISSUE TITLE
User input

### ISSUE THREAD

**Issue by mogiiee** [IEEE-VIT/concy-bot#17]
let the users know what input can be used in the daily [daily reminders](https://github.com/IEEE-VIT/concy-bot/blob/5088204fd57f412940f38b80d7118f3c068980e5/bot.py#L88) which is mentioned in the response (both for affirmative and the negative)

**Comment by z404** [comment]
id like to take this up

**Comment by mogiiee** [comment]
@z404 sure i am assigning it to you

**Comment by z404** [comment]
hi @mogiiee would you like the bot to tell the user what the valid inputs are at every reminder, or only if they enter something that the bot couldn't understand?

**Comment by mogiiee** [comment]
only when the bot does not understand sounds better @z404
