### ISSUE TITLE
Add: break loop feature

### ISSUE THREAD

**Issue by mogiiee** [IEEE-VIT/concy-bot#18]
add a feature to break the loop or stop the daily reminders if the user changes their mind [here](https://github.com/IEEE-VIT/concy-bot/blob/5088204fd57f412940f38b80d7118f3c068980e5/bot.py#L77)
It can either be a new command or just another alias for the existing command.

**Comment by Dhruv9449** [comment]
I'd like to do this task

**Comment by mogiiee** [comment]
sure @Dhruv9449 , i am assigning this to you. Happy coding

**Comment by mogiiee** [comment]
@Dhruv9449  are you still working on it ... can i assign it to someone else?
