### ISSUE TITLE
hourly reminders

### ISSUE THREAD

**Issue by mogiiee** [IEEE-VIT/concy-bot#3]
create a function which 

1. Takes input from the user about what they want to accomplish in the next hour.
2. Sends a reminder after 30 minutes to see how far they have come up with the task.
3. After the end of the hour asks the user if they have completed the task. 
The bot will stop sending notifications once the user tells that they have finished the work.

**Comment by sanz17** [comment]
i want to solve this issue

**Comment by hg242322** [comment]
I am assigning this issue to you. All the Best !!
