### ISSUE TITLE
pomodoro

### ISSUE THREAD

**Issue by mogiiee** [IEEE-VIT/concy-bot#5]
Create a function which which when called on discord will implement the Pomodoro method which is continuous concentration for 25 minutes and then a 5 minute break. So to break it down,

1. Set a timer for 25 minutes 
2. Notify the user after 25 minutes
3. Set the timer for 5 minutes (starting of the break)
4. Notify the user after 5 minutes that Pomodoro has ended

Read more about Pomodoro from [here](https://todoist.com/productivity-methods/pomodoro-technique)

**Comment by Anik-Bardhan** [comment]
@mogiiee can I be assigned to this?

**Comment by mogiiee** [comment]
@Anik-Bardhan  sure i am assigning this to you... all the best

**Comment by Bhargav-bit800** [comment]
@mogiiee can i be assigned to this
