### ISSUE TITLE
motivational quotes API

### ISSUE THREAD

**Issue by mogiiee** [IEEE-VIT/concy-bot#6]
Integrate an API (Application Programming Interface) which gets motivational quotes from the net and presents it to the users when called on discord.
we recommend using [this](https://github.com/lukePeavey/quotable) API but you are free to use any API of your liking.

**Comment by moazfarrukh** [comment]
can i be assigned this?

**Comment by hg242322** [comment]
I am assigning this issue to you. All the Best !!

**Comment by moazfarrukh** [comment]
#15

**Comment by nayan2306** [comment]
@hg242322  Can o do this I am the student of VIIT
