### ISSUE TITLE
daily-reminders

### ISSUE THREAD

**Issue by mogiiee** [IEEE-VIT/concy-bot#7]
create a function which

1. Takes input from the user about what they want to accomplish in the entire day.
2. Sends a reminder after 60 minutes to see how far they have come up with the task.
3. After the end of the day asks the user if they have completed the task.
4. The bot will stop sending notifications once the user tells that they have finished the work.

**Comment by Smelton01** [comment]
Can I be assigned this issue?

**Comment by hg242322** [comment]
I am assigning this issue to you. All the Best !!
